/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProvadorRouteImport } from './routes/provador'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin.config'
import { Route as AuthenticatedAdminEnvioRouteImport } from './routes/_authenticated/admin.envio'
import { Route as AuthenticatedAdminPedidosIndexRouteImport } from './routes/_authenticated/admin.pedidos.index'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated/admin.pedidos.$id'
import { Route as AuthenticatedAdminProdutosIndexRouteImport } from './routes/_authenticated/admin.produtos.index'
import { Route as AuthenticatedAdminProdutosIdRouteImport } from './routes/_authenticated/admin.produtos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvadorRoute = ProvadorRouteImport.update({
  id: '/provador',
  path: '/provador',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnvioRoute = AuthenticatedAdminEnvioRouteImport.update({
  id: '/envio',
  path: '/envio',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPedidosIndexRoute =
  AuthenticatedAdminPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/pedidos/$id',
    path: '/pedidos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutosIndexRoute =
  AuthenticatedAdminProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutosIdRoute =
  AuthenticatedAdminProdutosIdRouteImport.update({
    id: '/produtos/$id',
    path: '/produtos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/provador': typeof ProvadorRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/envio': typeof AuthenticatedAdminEnvioRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/pedidos/': typeof AuthenticatedAdminPedidosIndexRoute
  '/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/provador': typeof ProvadorRoute
  '/sobre': typeof SobreRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/envio': typeof AuthenticatedAdminEnvioRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosIndexRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/provador': typeof ProvadorRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/envio': typeof AuthenticatedAdminEnvioRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/_authenticated/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/_authenticated/admin/pedidos/': typeof AuthenticatedAdminPedidosIndexRoute
  '/_authenticated/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/checkout'
    | '/provador'
    | '/sobre'
    | '/admin'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/envio'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/checkout'
    | '/provador'
    | '/sobre'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/envio'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/pedidos'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/catalogo'
    | '/checkout'
    | '/provador'
    | '/sobre'
    | '/_authenticated/admin'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/envio'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pedidos/$id'
    | '/_authenticated/admin/produtos/$id'
    | '/_authenticated/admin/pedidos/'
    | '/_authenticated/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ProvadorRoute: typeof ProvadorRoute
  SobreRoute: typeof SobreRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provador': {
      id: '/provador'
      path: '/provador'
      fullPath: '/provador'
      preLoaderRoute: typeof ProvadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/envio': {
      id: '/_authenticated/admin/envio'
      path: '/envio'
      fullPath: '/admin/envio'
      preLoaderRoute: typeof AuthenticatedAdminEnvioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos/': {
      id: '/_authenticated/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos/': {
      id: '/_authenticated/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos/$id': {
      id: '/_authenticated/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminEnvioRoute: typeof AuthenticatedAdminEnvioRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
  AuthenticatedAdminProdutosIdRoute: typeof AuthenticatedAdminProdutosIdRoute
  AuthenticatedAdminPedidosIndexRoute: typeof AuthenticatedAdminPedidosIndexRoute
  AuthenticatedAdminProdutosIndexRoute: typeof AuthenticatedAdminProdutosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminEnvioRoute: AuthenticatedAdminEnvioRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  AuthenticatedAdminProdutosIdRoute: AuthenticatedAdminProdutosIdRoute,
  AuthenticatedAdminPedidosIndexRoute: AuthenticatedAdminPedidosIndexRoute,
  AuthenticatedAdminProdutosIndexRoute: AuthenticatedAdminProdutosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ProvadorRoute: ProvadorRoute,
  SobreRoute: SobreRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
